#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
TOTAL_MINUTES=16

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
ENV_FILE="$REPO_ROOT/.setup-mac.env"
LOCAL_FILE="$REPO_ROOT/local.nix"
NIX_BIN=$(command -v nix || true)
[[ -n "$NIX_BIN" ]] || NIX_BIN="/nix/var/nix/profiles/default/bin/nix"
[[ -x "$NIX_BIN" ]] || { warn "Install Nix before running this wizard."; exit 1; }

# Install the private-name guard before anything else can be committed from
# this clone. `.git/hooks` is per-clone and untracked, so a fresh machine has
# no guard until this runs.
"$REPO_ROOT/scripts/install-hooks.sh"

run_switch() {
  local mode="${1:-routine}"
  export NIX_CONFIG_LOCAL="$LOCAL_FILE"
  if [[ -x /run/current-system/sw/bin/darwin-rebuild ]]; then
    if [[ "$mode" == bootstrap ]]; then
      export NIX_CONFIG_SETUP_BOOTSTRAP=1
      sudo -A --preserve-env=NIX_CONFIG_LOCAL,NIX_CONFIG_SETUP_BOOTSTRAP \
        /run/current-system/sw/bin/darwin-rebuild switch --impure \
        --flake "path:$REPO_ROOT#example-mac"
      unset NIX_CONFIG_SETUP_BOOTSTRAP
    else
      sudo -A --preserve-env=NIX_CONFIG_LOCAL \
        /run/current-system/sw/bin/darwin-rebuild switch --impure \
        --flake "path:$REPO_ROOT#example-mac"
    fi
  else
    if [[ "$mode" == bootstrap ]]; then
      sudo env \
        NIX_CONFIG_LOCAL="$NIX_CONFIG_LOCAL" \
        NIX_CONFIG_SETUP_BOOTSTRAP=1 \
        NIX_CONFIG="extra-experimental-features = nix-command flakes" \
        /nix/var/nix/profiles/default/bin/nix \
        run nix-darwin/nix-darwin-26.05#darwin-rebuild -- \
        switch --impure --flake "path:$REPO_ROOT#example-mac"
    else
      sudo env \
        NIX_CONFIG_LOCAL="$NIX_CONFIG_LOCAL" \
        NIX_CONFIG="extra-experimental-features = nix-command flakes" \
        /nix/var/nix/profiles/default/bin/nix \
        run nix-darwin/nix-darwin-26.05#darwin-rebuild -- \
        switch --impure --flake "path:$REPO_ROOT#example-mac"
    fi
  fi
}

run_nix() {
  NIX_CONFIG="extra-experimental-features = nix-command flakes" \
    NIX_CONFIG_LOCAL="$LOCAL_FILE" "$NIX_BIN" "$@"
}

read_local_attr() {
  local attr="$1"
  SETUP_LOCAL="$LOCAL_FILE" \
    NIX_CONFIG="extra-experimental-features = nix-command flakes" \
    "$NIX_BIN" eval --impure --raw --expr \
    "(import (builtins.toPath (builtins.getEnv \"SETUP_LOCAL\"))).$attr"
}

read_local_optional_attr() {
  local attr="$1"
  SETUP_LOCAL="$LOCAL_FILE" \
    NIX_CONFIG="extra-experimental-features = nix-command flakes" "$NIX_BIN" eval --impure --raw --expr \
    "(let local = import (builtins.toPath (builtins.getEnv \"SETUP_LOCAL\")); value = local.$attr or null; in if value == null then \"\" else value)"
}

banner "Declarative Mac setup"

stage "Detect this Mac" 1
[[ "$(uname -s)" == "Darwin" ]] || { warn "This wizard supports macOS only."; exit 1; }
MAC_USER=$(id -un)
MAC_HOME="$HOME"
MAC_HOST=$(/usr/sbin/scutil --get LocalHostName)
case "$(uname -m)" in
  arm64) MAC_SYSTEM="aarch64-darwin" ;;
  x86_64) MAC_SYSTEM="x86_64-darwin" ;;
  *) warn "Unsupported Mac architecture: $(uname -m)"; exit 1 ;;
esac
say "Detected $MAC_USER on $MAC_HOST ($MAC_SYSTEM)."

stage "Connect to 1Password Connect" 2
# The one credential this Mac is given by hand. Everything that reads or writes
# 1Password afterwards (Git signing and push, AWS, the network share, the
# local.nix backup) goes through Connect with this token: never the `op` CLI,
# a service account, or the desktop application, and never a fallback.
CONNECT_ENV="$MAC_HOME/.config/op/connect.env"
CONNECT_NOTE=(/usr/bin/python3 "$REPO_ROOT/scripts/onepassword-connect-note.py")
connect_answers() {
  local host
  host=$(/usr/bin/sed -n 's/^OP_CONNECT_HOST=//p' "$CONNECT_ENV" 2>/dev/null)
  [[ -n "$host" ]] && /usr/bin/curl -fsS -m 5 -o /dev/null "$host/heartbeat"
}
if [[ -s "$CONNECT_ENV" ]] && connect_answers; then
  say "Using the existing Connect environment at $CONNECT_ENV."
else
  ask CONNECT_HOST "1Password Connect URL (e.g. http://192.168.1.10:8091):"
  [[ "$CONNECT_HOST" =~ ^https?://[^/]+/?$ ]] || { warn "That is not a Connect server URL."; exit 1; }
  CONNECT_HOST=${CONNECT_HOST%/}
  # Read here, never through ask_secret: the token must not reach .setup-mac.env.
  printf '%s' "  Connect access token (hidden; copy it from 1Password on your phone): "
  IFS= read -rs CONNECT_TOKEN
  printf '\n'
  [[ -n "$CONNECT_TOKEN" ]] || { warn "The Connect token cannot be empty."; exit 1; }
  mkdir -p "$(dirname "$CONNECT_ENV")"
  chmod 700 "$(dirname "$CONNECT_ENV")"
  connect_tmp=$(umask 077; mktemp "$CONNECT_ENV.tmp.XXXXXX")
  printf 'OP_CONNECT_HOST=%s\nOP_CONNECT_TOKEN=%s\n' "$CONNECT_HOST" "$CONNECT_TOKEN" > "$connect_tmp"
  unset CONNECT_TOKEN
  chmod 600 "$connect_tmp"
  mv "$connect_tmp" "$CONNECT_ENV"
  connect_answers || { warn "ERROR: Connect at $CONNECT_HOST does not answer. Join the network it is on (or its VPN) and rerun."; exit 1; }
  say "Wrote $CONNECT_ENV (mode 600)."
fi

stage "Restore local.nix from 1Password" 1
# Each Mac's local.nix lives in 1Password as the Secure Note
# "nix-config local.nix <hostname>", saved by every rebuild. A new Mac copies
# one and keeps its own macOS hostname; its first rebuild saves a new note
# under that name.
local_is_complete() {
  [[ -s "$LOCAL_FILE" ]] \
    && read_local_optional_attr "git.signingKeyReference" 2>/dev/null | grep -q '^op://' \
    && ! read_local_attr git.signingKey 2>/dev/null | grep -q 'AAAAAAAAAAAAAAAA'
}
if local_is_complete; then
  say "local.nix is already complete; keeping it."
else
  notes=$("${CONNECT_NOTE[@]}" "$CONNECT_ENV" list "nix-config local.nix ") \
    || { warn "ERROR: could not list local.nix notes through Connect (see above)."; exit 1; }
  [[ -n "$notes" ]] || { warn "ERROR: Connect sees no 'nix-config local.nix <hostname>' Secure Note. Check the token's vault access."; exit 1; }
  if [[ $(printf '%s\n' "$notes" | wc -l | tr -d ' ') -eq 1 ]]; then
    choice="$notes"
  elif match=$(printf '%s\n' "$notes" | awk -F'\t' -v t="nix-config local.nix $MAC_HOST" '$2 == t') && [[ -n "$match" ]]; then
    choice="$match"
  else
    say "Several Macs are stored in 1Password:"
    printf '%s\n' "$notes" | awk -F'\t' '{ printf "    %d) %s  (%s)\n", NR, substr($2, 22), $1 }'
    ask NOTE_NUMBER "Number of the Mac this one replaces:"
    choice=$(printf '%s\n' "$notes" | sed -n "${NOTE_NUMBER}p")
    [[ -n "$choice" ]] || { warn "No such number."; exit 1; }
  fi
  note_vault=$(printf '%s' "$choice" | cut -f1)
  note_title=$(printf '%s' "$choice" | cut -f2)
  restore_dir=$(mktemp -d "$REPO_ROOT/.local.nix.restore.XXXXXX")
  trap 'rm -rf "$restore_dir"' EXIT
  restored="$restore_dir/local.nix"
  "${CONNECT_NOTE[@]}" "$CONNECT_ENV" get "$note_vault" "$note_title" "$restored" \
    || { warn "ERROR: could not read '$note_title' through Connect (see above)."; exit 1; }
  for attr_and_expected in "user|$MAC_USER" "system|$MAC_SYSTEM" "homeDirectory|$MAC_HOME"; do
    attr=${attr_and_expected%%|*}
    expected=${attr_and_expected#*|}
    if ! actual=$(SETUP_LOCAL="$restored" NIX_CONFIG="extra-experimental-features = nix-command flakes" \
        "$NIX_BIN" eval --impure --raw --expr \
        "(import (builtins.toPath (builtins.getEnv \"SETUP_LOCAL\"))).$attr" 2>/dev/null) \
        || [[ "$actual" != "$expected" ]]; then
      warn "ERROR: '$note_title' expects $attr = '${actual:-?}', but this Mac has '$expected'."
      [[ "$attr" == user ]] && say "Create the macOS account with short name '$actual' (Setup Assistant), sign in to it, and rerun."
      exit 1
    fi
  done
  # This Mac keeps the name macOS gave it: take the old Mac's settings but
  # record this Mac's own hostname, so nothing is renamed and every rebuild
  # backs up under this Mac's name.
  if [[ $(grep -c '^  hostName = ".*";$' "$restored") -ne 1 ]]; then
    warn "ERROR: the stored local.nix does not have exactly one 'hostName = \"...\";' line."
    exit 1
  fi
  /usr/bin/sed -i '' "s/^  hostName = \".*\";\$/  hostName = \"$MAC_HOST\";/" "$restored"
  [[ "$(SETUP_LOCAL="$restored" NIX_CONFIG="extra-experimental-features = nix-command flakes" \
      "$NIX_BIN" eval --impure --raw --expr \
      '(import (builtins.toPath (builtins.getEnv "SETUP_LOCAL"))).hostName')" == "$MAC_HOST" ]] \
    || { warn "ERROR: could not set hostName to $MAC_HOST in the restored local.nix."; exit 1; }
  chmod 600 "$restored"
  mv "$restored" "$LOCAL_FILE"
  rm -rf "$restore_dir"
  trap - EXIT
  say "Restored local.nix from '$note_title' for this Mac ($MAC_HOST)."
fi

stage "Install the declared system" 8
# Install-only first generation: applications and tools, credential checks deferred.
cd "$REPO_ROOT"
export NIX_CONFIG_SETUP_BOOTSTRAP=1
run_nix build --no-link --impure .#darwinConfigurations.example-mac.system
run_switch bootstrap
unset NIX_CONFIG_SETUP_BOOTSTRAP

stage "Bootstrap runtime credentials" 1
PROFILE_BIN="/etc/profiles/per-user/$MAC_USER/bin"
NETWORK_SHARE_BOOTSTRAP="$PROFILE_BIN/nix-config-bootstrap-network-share-password"
NETWORK_SERVER=$(read_local_optional_attr "networkShares.server" || true)
NETWORK_ACCOUNT=$(read_local_optional_attr "networkShares.account" || true)
NETWORK_PASSWORD_REFERENCE=$(read_local_optional_attr "networkShares.passwordReference" || true)
if [[ -n "$NETWORK_SERVER" && -n "$NETWORK_ACCOUNT" && -n "$NETWORK_PASSWORD_REFERENCE" ]]; then
  if [[ ! -x "$NETWORK_SHARE_BOOTSTRAP" ]]; then
    warn "The generated network-share bootstrap command is missing; rerun the first generation."
    exit 1
  fi
  "$NETWORK_SHARE_BOOTSTRAP" "$NETWORK_SERVER" "$NETWORK_ACCOUNT" "$NETWORK_PASSWORD_REFERENCE"
else
  say "No network-share password bootstrap is configured."
fi

stage "Apply the final configuration" 3
# The routine rebuild: final switch, then the local.nix backup saved to
# 1Password through Connect under this Mac's name.
"$REPO_ROOT/scripts/rebuild.sh"
# GitHub pushes go through the declared Connect-backed SSH transport.
git -C "$REPO_ROOT" remote set-url origin git@github.com:DivMode/nix-config.git

finish
note "Nothing on this Mac uses the 1Password app or CLI; Git, AWS and the network share read through Connect."
