#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
TOTAL_MINUTES=17

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
ENV_FILE="$REPO_ROOT/.setup-mac.env"
LOCAL_FILE="$REPO_ROOT/local.nix"
BOOTSTRAP_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
BOOTSTRAP_ITEM_ID="aaaaaaaaaaaaaaaaaaaaaaaaaa"
NIX_BIN=$(command -v nix || true)
[[ -n "$NIX_BIN" ]] || NIX_BIN="/nix/var/nix/profiles/default/bin/nix"
[[ -x "$NIX_BIN" ]] || { warn "Install Nix before running this wizard."; exit 1; }

# Install the private-name guard before anything else can be committed from
# this clone. `.git/hooks` is per-clone and untracked, so a fresh machine has
# no guard until this runs.
"$REPO_ROOT/scripts/install-hooks.sh"

validate_nix_text() {
  local label="$1" value="$2"
  if [[ "$value" == *'${'* ]] || printf '%s' "$value" | LC_ALL=C grep -q '[[:cntrl:]]'; then
    warn "$label contains characters that cannot be written safely to local.nix."
    exit 1
  fi
}

nix_escape() {
  local value="$1"
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  printf '%s' "$value"
}

write_local_nix() {
  local git_name="$1" git_email="$2" signing_key="$3" key_ids_file="$4" signing_reference="$5" tmp
  tmp=$(mktemp "$REPO_ROOT/.local.nix.XXXXXX")
  {
    printf '{\n'
    printf '  user = "%s";\n' "$(nix_escape "$MAC_USER")"
    printf '  hostName = "%s";\n' "$(nix_escape "$MAC_HOST")"
    printf '  system = "%s";\n' "$MAC_SYSTEM"
    printf '  homeDirectory = "%s";\n' "$(nix_escape "$MAC_HOME")"
    printf '  git = {\n'
    printf '    name = "%s";\n' "$(nix_escape "$git_name")"
    printf '    email = "%s";\n' "$(nix_escape "$git_email")"
    printf '    signingKey = "%s";\n' "$(nix_escape "$signing_key")"
    printf '    signingKeyReference = "%s";\n' "$(nix_escape "$signing_reference")"
    printf '  };\n'
    printf '  onePassword.sshAgentKeyIds = [\n'
    while IFS= read -r item_id; do
      [[ -n "$item_id" ]] && printf '    "%s"\n' "$item_id"
    done < "$key_ids_file"
    printf '  ];\n'
    # The vault this host's local.nix is backed up to. Written here so that
    # scripts/rebuild.sh reads it from local.nix on every later run and the
    # name never returns to a tracked file.
    if [[ -n "${OP_VAULT:-}" ]]; then
      printf '  onePassword.vault = "%s";\n' "$(nix_escape "$OP_VAULT")"
    fi
    printf '}\n'
  } > "$tmp"
  chmod 600 "$tmp"
  mv "$tmp" "$LOCAL_FILE"
}

run_switch() {
  local mode="${1:-routine}"
  export NIX_CONFIG_LOCAL="$LOCAL_FILE"
  if [[ -x /run/current-system/sw/bin/darwin-rebuild ]]; then
    if [[ "$mode" == bootstrap ]]; then
      export NIX_CONFIG_SETUP_BOOTSTRAP=1
      sudo -A --preserve-env=NIX_CONFIG_LOCAL,NIX_CONFIG_SETUP_BOOTSTRAP \
        /run/current-system/sw/bin/darwin-rebuild switch --impure \
        --flake "path:$REPO_ROOT#example-mac"
      unset NIX_CONFIG_SETUP_BOOTSTRAP
    else
      sudo -A --preserve-env=NIX_CONFIG_LOCAL \
        /run/current-system/sw/bin/darwin-rebuild switch --impure \
        --flake "path:$REPO_ROOT#example-mac"
    fi
  else
    if [[ "$mode" == bootstrap ]]; then
      sudo env \
        NIX_CONFIG_LOCAL="$NIX_CONFIG_LOCAL" \
        NIX_CONFIG_SETUP_BOOTSTRAP=1 \
        NIX_CONFIG="extra-experimental-features = nix-command flakes" \
        /nix/var/nix/profiles/default/bin/nix \
        run nix-darwin/nix-darwin-26.05#darwin-rebuild -- \
        switch --impure --flake "path:$REPO_ROOT#example-mac"
    else
      sudo env \
        NIX_CONFIG_LOCAL="$NIX_CONFIG_LOCAL" \
        NIX_CONFIG="extra-experimental-features = nix-command flakes" \
        /nix/var/nix/profiles/default/bin/nix \
        run nix-darwin/nix-darwin-26.05#darwin-rebuild -- \
        switch --impure --flake "path:$REPO_ROOT#example-mac"
    fi
  fi
}

run_nix() {
  NIX_CONFIG="extra-experimental-features = nix-command flakes" \
    NIX_CONFIG_LOCAL="$LOCAL_FILE" "$NIX_BIN" "$@"
}

read_local_attr() {
  local attr="$1"
  SETUP_LOCAL="$LOCAL_FILE" \
    NIX_CONFIG="extra-experimental-features = nix-command flakes" \
    "$NIX_BIN" eval --impure --raw --expr \
    "(import (builtins.toPath (builtins.getEnv \"SETUP_LOCAL\"))).$attr"
}

read_local_optional_attr() {
  local attr="$1"
  SETUP_LOCAL="$LOCAL_FILE" \
    NIX_CONFIG="extra-experimental-features = nix-command flakes" "$NIX_BIN" eval --impure --raw --expr \
    "(let local = import (builtins.toPath (builtins.getEnv \"SETUP_LOCAL\")); value = local.$attr or null; in if value == null then \"\" else value)"
}

banner "Declarative Mac setup"

stage "Detect this Mac" 1
[[ "$(uname -s)" == "Darwin" ]] || { warn "This wizard supports macOS only."; exit 1; }
MAC_USER=$(id -un)
MAC_HOME="$HOME"
MAC_HOST=$(/usr/sbin/scutil --get LocalHostName)
case "$(uname -m)" in
  arm64) MAC_SYSTEM="aarch64-darwin" ;;
  x86_64) MAC_SYSTEM="x86_64-darwin" ;;
  *) warn "Unsupported Mac architecture: $(uname -m)"; exit 1 ;;
esac
say "Detected $MAC_USER on $MAC_HOST ($MAC_SYSTEM)."

stage "Create bootstrap identity" 1
if [[ -e "$LOCAL_FILE" ]]; then
  stale_local=0
  for attr_and_expected in \
    "user|$MAC_USER" \
    "hostName|$MAC_HOST" \
    "system|$MAC_SYSTEM" \
    "homeDirectory|$MAC_HOME"; do
    attr=${attr_and_expected%%|*}
    expected=${attr_and_expected#*|}
    if ! actual=$(read_local_attr "$attr" 2>/dev/null) || [[ "$actual" != "$expected" ]]; then
      stale_local=1
    fi
  done

  if [[ "$stale_local" -eq 1 ]]; then
    warn "Existing local.nix targets a different or invalid Mac."
    if confirm "Replace it with detected host fields and bootstrap placeholders?"; then
      bootstrap_ids=$(mktemp)
      printf '%s\n' "$BOOTSTRAP_ITEM_ID" > "$bootstrap_ids"
      write_local_nix "Bootstrap User" "bootstrap@example.invalid" "$BOOTSTRAP_KEY" "$bootstrap_ids" "op://Automation/Git signing/private key?ssh-format=openssh"
      rm -f "$bootstrap_ids"
    else
      exit 1
    fi
  else
    say "Existing local.nix matches this Mac; preserving it for the first switch."
  fi
else
  bootstrap_ids=$(mktemp)
  printf '%s\n' "$BOOTSTRAP_ITEM_ID" > "$bootstrap_ids"
  write_local_nix "Bootstrap User" "bootstrap@example.invalid" "$BOOTSTRAP_KEY" "$bootstrap_ids" "op://Automation/Git signing/private key?ssh-format=openssh"
  rm -f "$bootstrap_ids"
  say "Created ignored local.nix with detected Mac fields and public placeholders."
fi

stage "Install the declared system" 8
say "This first switch installs every declared application."
if confirm "Validate, build, and apply the first Nix generation now?"; then
  cd "$REPO_ROOT"
  # The first system is an install-only generation. This impure evaluation
  # flag is consumed by the Nix modules while generating activation, so it does
  # not depend on an environment hop through nix-darwin's user activation.
  export NIX_CONFIG_SETUP_BOOTSTRAP=1
  run_nix flake check --impure
  run_nix build --no-link --impure \
    .#darwinConfigurations.example-mac.system
  run_switch bootstrap
  unset NIX_CONFIG_SETUP_BOOTSTRAP
else
  warn "The wizard cannot continue until the first switch succeeds."
  exit 1
fi

stage "Connect to 1Password Connect" 2
# The one credential this Mac is given by hand. Everything that reads 1Password
# afterwards (Git signing and push, AWS, the network share, the local.nix
# restore below) goes through Connect with this token: never the `op` CLI, a
# service account, or the desktop application, and never a fallback.
CONNECT_ENV="$MAC_HOME/.config/op/connect.env"
CONNECT_PY=(/usr/bin/python3 "$REPO_ROOT/scripts/onepassword-connect-document.py")
if [[ -s "$CONNECT_ENV" ]] && confirm "Keep the existing Connect environment at $CONNECT_ENV?"; then
  say "Keeping $CONNECT_ENV."
else
  ask CONNECT_HOST "1Password Connect URL (https, or http on your LAN, e.g. http://192.168.1.10:8091):"
  [[ "$CONNECT_HOST" =~ ^https?://[^/]+/?$ ]] || { warn "That is not a Connect server URL."; exit 1; }
  CONNECT_HOST=${CONNECT_HOST%/}
  # Read here, never through ask_secret: the token must not reach .setup-mac.env.
  printf '%s' "  Connect access token (hidden): "
  IFS= read -rs CONNECT_TOKEN
  printf '\n'
  [[ -n "$CONNECT_TOKEN" ]] || { warn "The Connect token cannot be empty."; exit 1; }
  mkdir -p "$(dirname "$CONNECT_ENV")"
  chmod 700 "$(dirname "$CONNECT_ENV")"
  connect_tmp=$(umask 077; mktemp "$CONNECT_ENV.tmp.XXXXXX")
  printf 'OP_CONNECT_HOST=%s\nOP_CONNECT_TOKEN=%s\n' "$CONNECT_HOST" "$CONNECT_TOKEN" > "$connect_tmp"
  unset CONNECT_TOKEN
  chmod 600 "$connect_tmp"
  mv "$connect_tmp" "$CONNECT_ENV"
  say "Wrote $CONNECT_ENV (mode 600)."
fi
connect_host=$(/usr/bin/sed -n 's/^OP_CONNECT_HOST=//p' "$CONNECT_ENV")
if ! /usr/bin/curl -fsS -m 5 -o /dev/null "$connect_host/heartbeat"; then
  warn "ERROR: Connect at $connect_host does not answer. This Mac must reach it (same network or VPN) before setup can continue."
  exit 1
fi
say "Connect at $connect_host answers."

stage "Restore local.nix through Connect" 1
# Each host's local.nix is stored in 1Password as a Document titled
# "nix-config local.nix <LocalHostName>". Restoring it is what brings back the
# Git identity, item IDs, Connect host and AWS profiles without retyping.
IDENTITY_RESTORED=0
if [[ -s "$LOCAL_FILE" ]] && read_local_optional_attr "git.signingKeyReference" 2>/dev/null | grep -q '^op://' \
    && [[ "$(read_local_attr hostName 2>/dev/null)" == "$MAC_HOST" ]] \
    && ! read_local_attr git.signingKey 2>/dev/null | grep -q 'AAAAAAAAAAAAAAAA'; then
  IDENTITY_RESTORED=1
  say "local.nix already holds this Mac's full identity; nothing to restore."
else
  LOCAL_DOC_TITLE="nix-config local.nix $MAC_HOST"
  # The vault name is asked, never written into this public file. It is
  # remembered in the ignored .setup-mac.env for reruns.
  [[ -n "$(_existing OP_VAULT || true)" ]] || write_env OP_VAULT "Homelab"
  ask OP_VAULT "1Password vault holding this host's local.nix:"
  validate_nix_text "The vault name" "$OP_VAULT"
  restored="$REPO_ROOT/.local.nix.restore.$$"
  if ! "${CONNECT_PY[@]}" "$CONNECT_ENV" "$OP_VAULT" "$LOCAL_DOC_TITLE" "$restored"; then
    rm -f "$restored"
    warn "ERROR: no document titled '$LOCAL_DOC_TITLE' could be read through Connect (see above)."
    say "Fix: copy local.nix from your old Mac into $REPO_ROOT, set its hostName to \"$MAC_HOST\","
    say "or rename this Mac to the old hostName (System Settings → General → Sharing → Local hostname), then rerun."
    exit 1
  fi
  for attr_and_expected in "user|$MAC_USER" "hostName|$MAC_HOST" "system|$MAC_SYSTEM" "homeDirectory|$MAC_HOME"; do
    attr=${attr_and_expected%%|*}
    expected=${attr_and_expected#*|}
    if ! actual=$(SETUP_LOCAL="$restored" NIX_CONFIG="extra-experimental-features = nix-command flakes" \
        "$NIX_BIN" eval --impure --raw --expr \
        "(import (builtins.toPath (builtins.getEnv \"SETUP_LOCAL\"))).$attr" 2>/dev/null) \
        || [[ "$actual" != "$expected" ]]; then
      rm -f "$restored"
      warn "ERROR: the stored local.nix has $attr = '${actual:-?}', but this Mac is '$expected'."
      say "Fix: edit that field in a copy of local.nix placed at $LOCAL_FILE, then rerun."
      exit 1
    fi
  done
  chmod 600 "$restored"
  mv "$restored" "$LOCAL_FILE"
  IDENTITY_RESTORED=1
  say "Restored local.nix for $MAC_HOST through Connect."
fi

stage "Bootstrap runtime credentials" 1
PROFILE_BIN="/etc/profiles/per-user/$MAC_USER/bin"
NETWORK_SHARE_BOOTSTRAP="$PROFILE_BIN/nix-config-bootstrap-network-share-password"
NETWORK_SERVER=$(read_local_optional_attr "networkShares.server" || true)
NETWORK_ACCOUNT=$(read_local_optional_attr "networkShares.account" || true)
NETWORK_PASSWORD_REFERENCE=$(read_local_optional_attr "networkShares.passwordReference" || true)
if [[ -n "$NETWORK_SERVER" && -n "$NETWORK_ACCOUNT" && -n "$NETWORK_PASSWORD_REFERENCE" ]]; then
  if [[ ! -x "$NETWORK_SHARE_BOOTSTRAP" ]]; then
    warn "The generated network-share bootstrap command is missing; rerun the first generation."
    exit 1
  fi
  "$NETWORK_SHARE_BOOTSTRAP" "$NETWORK_SERVER" "$NETWORK_ACCOUNT" "$NETWORK_PASSWORD_REFERENCE"
else
  say "No network-share password bootstrap is configured."
fi

stage "Apply the final identity" 3
if confirm "Validate and apply the final local identity now?"; then
  cd "$REPO_ROOT"
  run_nix flake check --impure
  run_nix build --no-link --impure \
    .#darwinConfigurations.example-mac.system
  run_switch
else
  SKIPPED+=("final Nix switch")
fi

finish
note "Nothing on this Mac uses the 1Password app or CLI; Git, AWS and the network share read through Connect."
