#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
TOTAL_MINUTES=21

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
ENV_FILE="$REPO_ROOT/.setup-mac.env"
LOCAL_FILE="$REPO_ROOT/local.nix"
BOOTSTRAP_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
BOOTSTRAP_ITEM_ID="aaaaaaaaaaaaaaaaaaaaaaaaaa"
NIX_BIN=$(command -v nix || true)
[[ -n "$NIX_BIN" ]] || NIX_BIN="/nix/var/nix/profiles/default/bin/nix"
[[ -x "$NIX_BIN" ]] || { warn "Install Nix before running this wizard."; exit 1; }

validate_nix_text() {
  local label="$1" value="$2"
  if [[ "$value" == *'${'* ]] || printf '%s' "$value" | LC_ALL=C grep -q '[[:cntrl:]]'; then
    warn "$label contains characters that cannot be written safely to local.nix."
    exit 1
  fi
}

nix_escape() {
  local value="$1"
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  printf '%s' "$value"
}

write_local_nix() {
  local git_name="$1" git_email="$2" signing_key="$3" key_ids_file="$4" tmp
  tmp=$(mktemp "$REPO_ROOT/.local.nix.XXXXXX")
  {
    printf '{\n'
    printf '  user = "%s";\n' "$(nix_escape "$MAC_USER")"
    printf '  hostName = "%s";\n' "$(nix_escape "$MAC_HOST")"
    printf '  system = "%s";\n' "$MAC_SYSTEM"
    printf '  homeDirectory = "%s";\n' "$(nix_escape "$MAC_HOME")"
    printf '  git = {\n'
    printf '    name = "%s";\n' "$(nix_escape "$git_name")"
    printf '    email = "%s";\n' "$(nix_escape "$git_email")"
    printf '    signingKey = "%s";\n' "$(nix_escape "$signing_key")"
    printf '  };\n'
    printf '  onePassword.sshAgentKeyIds = [\n'
    while IFS= read -r item_id; do
      [[ -n "$item_id" ]] && printf '    "%s"\n' "$item_id"
    done < "$key_ids_file"
    printf '  ];\n'
    printf '}\n'
  } > "$tmp"
  chmod 600 "$tmp"
  mv "$tmp" "$LOCAL_FILE"
}

run_switch() {
  export NIX_CONFIG_LOCAL="$LOCAL_FILE"
  if [[ -x /run/current-system/sw/bin/darwin-rebuild ]]; then
    sudo env NIX_CONFIG_LOCAL="$NIX_CONFIG_LOCAL" \
      /run/current-system/sw/bin/darwin-rebuild switch --impure \
      --flake "path:$REPO_ROOT#example-mac"
  else
    sudo env \
      NIX_CONFIG_LOCAL="$NIX_CONFIG_LOCAL" \
      NIX_CONFIG="extra-experimental-features = nix-command flakes" \
      /nix/var/nix/profiles/default/bin/nix \
      run nix-darwin/nix-darwin-26.05#darwin-rebuild -- \
      switch --impure --flake "path:$REPO_ROOT#example-mac"
  fi
}

run_nix() {
  NIX_CONFIG="extra-experimental-features = nix-command flakes" \
    NIX_CONFIG_LOCAL="$LOCAL_FILE" "$NIX_BIN" "$@"
}

read_local_attr() {
  local attr="$1"
  SETUP_LOCAL="$LOCAL_FILE" \
    NIX_CONFIG="extra-experimental-features = nix-command flakes" \
    "$NIX_BIN" eval --impure --raw --expr \
    "(import (builtins.toPath (builtins.getEnv \"SETUP_LOCAL\"))).$attr"
}

banner "Declarative Mac setup"

stage "Detect this Mac" 1
[[ "$(uname -s)" == "Darwin" ]] || { warn "This wizard supports macOS only."; exit 1; }
MAC_USER=$(id -un)
MAC_HOME="$HOME"
MAC_HOST=$(/usr/sbin/scutil --get LocalHostName)
case "$(uname -m)" in
  arm64) MAC_SYSTEM="aarch64-darwin" ;;
  x86_64) MAC_SYSTEM="x86_64-darwin" ;;
  *) warn "Unsupported Mac architecture: $(uname -m)"; exit 1 ;;
esac
say "Detected $MAC_USER on $MAC_HOST ($MAC_SYSTEM)."

stage "Create bootstrap identity" 1
if [[ -e "$LOCAL_FILE" ]]; then
  stale_local=0
  for attr_and_expected in \
    "user|$MAC_USER" \
    "hostName|$MAC_HOST" \
    "system|$MAC_SYSTEM" \
    "homeDirectory|$MAC_HOME"; do
    attr=${attr_and_expected%%|*}
    expected=${attr_and_expected#*|}
    if ! actual=$(read_local_attr "$attr" 2>/dev/null) || [[ "$actual" != "$expected" ]]; then
      stale_local=1
    fi
  done

  if [[ "$stale_local" -eq 1 ]]; then
    warn "Existing local.nix targets a different or invalid Mac."
    if confirm "Replace it with detected host fields and bootstrap placeholders?"; then
      bootstrap_ids=$(mktemp)
      printf '%s\n' "$BOOTSTRAP_ITEM_ID" > "$bootstrap_ids"
      write_local_nix "Bootstrap User" "bootstrap@example.invalid" "$BOOTSTRAP_KEY" "$bootstrap_ids"
      rm -f "$bootstrap_ids"
    else
      exit 1
    fi
  else
    say "Existing local.nix matches this Mac; preserving it for the first switch."
  fi
else
  bootstrap_ids=$(mktemp)
  printf '%s\n' "$BOOTSTRAP_ITEM_ID" > "$bootstrap_ids"
  write_local_nix "Bootstrap User" "bootstrap@example.invalid" "$BOOTSTRAP_KEY" "$bootstrap_ids"
  rm -f "$bootstrap_ids"
  say "Created ignored local.nix with detected Mac fields and public placeholders."
fi

stage "Install the declared system" 8
say "This first switch installs 1Password and every other declared application."
if confirm "Validate, build, and apply the first Nix generation now?"; then
  cd "$REPO_ROOT"
  run_nix flake check --impure
  run_nix build --no-link --impure \
    .#darwinConfigurations.example-mac.system
  run_switch
else
  warn "The wizard cannot continue until the first switch installs 1Password and its CLI."
  exit 1
fi

stage "Sign in to 1Password" 3
open -a "1Password"
step "Sign in and unlock 1Password."
step "Open Settings → Developer and enable 'Use the SSH Agent'."
step "Enable the 1Password CLI integration so this wizard can discover public SSH metadata."
pause "Press Enter after those settings are enabled."

stage "Restore local.nix from 1Password" 1
# The canonical local.nix for each host lives in 1Password as a Document item
# titled "nix-config local.nix <LocalHostName>" (vault <vault>). Restoring
# it here is what makes a wiped machine a no-retyping setup: the Connect host,
# the 1Password item IDs, and the AWS profile wiring all come back without a
# human ever knowing them. scripts/rebuild.sh re-uploads the stored copy after
# every activation whose local.nix differs, and the identity stage below
# uploads a fresh copy when it runs (first-ever setup of a brand-new host).
BREW_PREFIX=$([[ "$MAC_SYSTEM" == "aarch64-darwin" ]] && printf /opt/homebrew || printf /usr/local)
OP="$BREW_PREFIX/bin/op"
LOCAL_DOC_TITLE="nix-config local.nix $MAC_HOST"
LOCAL_DOC_VAULT="<vault>"
IDENTITY_RESTORED=0
if [[ -x "$OP" ]]; then
  restored=$(mktemp "$REPO_ROOT/.local.nix.restore.XXXXXX")
  if "$OP" document get "$LOCAL_DOC_TITLE" --vault "$LOCAL_DOC_VAULT" > "$restored" 2>/dev/null \
      && [[ -s "$restored" ]]; then
    restore_ok=1
    for attr_and_expected in \
      "user|$MAC_USER" \
      "hostName|$MAC_HOST" \
      "system|$MAC_SYSTEM" \
      "homeDirectory|$MAC_HOME"; do
      attr=${attr_and_expected%%|*}
      expected=${attr_and_expected#*|}
      if ! actual=$(SETUP_LOCAL="$restored" \
          NIX_CONFIG="extra-experimental-features = nix-command flakes" \
          "$NIX_BIN" eval --impure --raw --expr \
          "(import (builtins.toPath (builtins.getEnv \"SETUP_LOCAL\"))).$attr" 2>/dev/null) \
          || [[ "$actual" != "$expected" ]]; then
        restore_ok=0
      fi
    done
    if [[ "$restore_ok" -eq 1 ]]; then
      chmod 600 "$restored"
      mv "$restored" "$LOCAL_FILE"
      IDENTITY_RESTORED=1
      say "Restored local.nix for $MAC_HOST from 1Password — nothing to retype."
    else
      rm -f "$restored"
      warn "The stored local.nix does not match this Mac; falling back to the identity wizard."
    fi
  else
    rm -f "$restored"
    say "No stored local.nix for $MAC_HOST — the identity wizard will create and upload one."
  fi
else
  warn "1Password CLI missing; continuing with the identity wizard."
fi

stage "Choose Git identity and SSH keys" 4
if [[ "$IDENTITY_RESTORED" -eq 1 ]]; then
  say "Skipped — local.nix was restored from 1Password."
else
ask GIT_NAME "Public Git author name:"
ask GIT_EMAIL "Git-host-verified public commit email:"
[[ -n "$GIT_NAME" ]] || { warn "Git author name cannot be empty."; exit 1; }
[[ "$GIT_EMAIL" == *@* ]] || { warn "Git email must contain @."; exit 1; }
validate_nix_text "Git author name" "$GIT_NAME"
validate_nix_text "Git email" "$GIT_EMAIL"
write_env GIT_NAME "$GIT_NAME"
write_env GIT_EMAIL "$GIT_EMAIL"

BREW_PREFIX=$([[ "$MAC_SYSTEM" == "aarch64-darwin" ]] && printf /opt/homebrew || printf /usr/local)
OP="$BREW_PREFIX/bin/op"
JQ="/etc/profiles/per-user/$MAC_USER/bin/jq"
[[ -x "$OP" ]] || { warn "1Password CLI is missing; rerun the first switch."; exit 1; }
[[ -x "$JQ" ]] || { warn "jq is missing; rerun the first switch."; exit 1; }

keys_json=$(mktemp)
keys_tsv=$(mktemp)
ordered_ids=$(mktemp)
trap 'rm -f "$keys_json" "$keys_tsv" "$ordered_ids"' EXIT
"$OP" item list --categories "SSH Key" --format json > "$keys_json"
"$JQ" -r '.[] | [.id, .title, .vault.name] | @tsv' "$keys_json" > "$keys_tsv"
key_count=$(wc -l < "$keys_tsv" | tr -d ' ')
[[ "$key_count" -gt 0 ]] || { warn "No SSH Key items are available in 1Password."; exit 1; }

say "Available SSH keys:"
awk -F '\t' '{ printf "  %d. %s (%s)\n", NR, $2, $3 }' "$keys_tsv"
ask SIGNING_KEY_NUMBER "Number of the Git signing key:"
case "$SIGNING_KEY_NUMBER" in *[!0-9]*|'') warn "Enter a number from the list."; exit 1 ;; esac
[[ "$SIGNING_KEY_NUMBER" -ge 1 && "$SIGNING_KEY_NUMBER" -le "$key_count" ]] \
  || { warn "Signing-key selection is out of range."; exit 1; }

selected_id=$(sed -n "${SIGNING_KEY_NUMBER}p" "$keys_tsv" | cut -f1)
signing_key=$("$OP" item get "$selected_id" --fields "public key")
[[ "$signing_key" == ssh-ed25519\ * ]] \
  || { warn "The selected item does not expose an Ed25519 public key."; exit 1; }
signing_key=$(printf '%s\n' "$signing_key" | awk '{ print $1 " " $2 }')
printf '%s\n' "$selected_id" > "$ordered_ids"
ask ADDITIONAL_KEY_NUMBERS "Additional key numbers to offer (comma-separated, blank for none, or 'all'):"
if [[ "$ADDITIONAL_KEY_NUMBERS" == "all" ]]; then
  awk -F '\t' -v selected="$selected_id" '$1 != selected { print $1 }' "$keys_tsv" >> "$ordered_ids"
elif [[ -n "$ADDITIONAL_KEY_NUMBERS" ]]; then
  for key_number in ${ADDITIONAL_KEY_NUMBERS//,/ }; do
    case "$key_number" in *[!0-9]*|'') warn "Additional key selections must be numbers."; exit 1 ;; esac
    [[ "$key_number" -ge 1 && "$key_number" -le "$key_count" ]] \
      || { warn "Additional key selection is out of range."; exit 1; }
    item_id=$(sed -n "${key_number}p" "$keys_tsv" | cut -f1)
    grep -qx "$item_id" "$ordered_ids" || printf '%s\n' "$item_id" >> "$ordered_ids"
  done
fi
if confirm "Replace local.nix with the detected host and selected Git/SSH metadata?"; then
  write_local_nix "$GIT_NAME" "$GIT_EMAIL" "$signing_key" "$ordered_ids"
else
  warn "No local identity was changed."
  exit 1
fi
say "Wrote public identity and ordered 1Password item IDs to ignored local.nix."

# First-ever setup of this host: store the freshly written local.nix so the
# NEXT wipe of this machine restores it without retyping anything. Deploy
# wiring (Connect host, item IDs, AWS profiles) added to local.nix later is
# captured by the rebuild.sh sync, not here.
if "$OP" document get "$LOCAL_DOC_TITLE" --vault "$LOCAL_DOC_VAULT" >/dev/null 2>&1; then
  if "$OP" document edit "$LOCAL_DOC_TITLE" "$LOCAL_FILE" --vault "$LOCAL_DOC_VAULT" >/dev/null 2>&1; then
    say "Updated the stored local.nix in 1Password ($LOCAL_DOC_TITLE)."
  else
    warn "Could not update the stored local.nix; scripts/rebuild.sh will retry after activation."
  fi
else
  if "$OP" document create "$LOCAL_FILE" --title "$LOCAL_DOC_TITLE" --vault "$LOCAL_DOC_VAULT" --file-name local.nix >/dev/null 2>&1; then
    say "Stored local.nix in 1Password for future restores ($LOCAL_DOC_TITLE)."
  else
    warn "Could not store local.nix; scripts/rebuild.sh will retry after activation."
  fi
fi
fi

stage "Apply the final identity" 3
if confirm "Validate and apply the final local identity now?"; then
  cd "$REPO_ROOT"
  run_nix flake check --impure
  run_nix build --no-link --impure \
    .#darwinConfigurations.example-mac.system
  run_switch
else
  SKIPPED+=("final Nix switch")
fi

finish
note "1Password will require consent the first time an application uses each private SSH key."
